### PR TITLE
Add webpack_config; document CF_TOKEN export

### PR DESCRIPTION
**Pull request by limakzi**
This patch:
- Configures webpack.config in Wrangle.
- Documents CF_API_TOKEN export.

### CODE REVIEW

**Comment by dhaynespls** [comment]
Hey! 

Good catch with the wrangler config. 

You don't necessarily need the CF_API_TOKEN environment variable as you should be using https://github.com/cloudflare/wrangler#-config with an scoped token. 

That said, I forgot to document that! If you could add a link to that up in section 2 that would be great.

**Comment by limakzi** [comment]
No worries. Thank you for your feedback.

- I would say, keeping the token in environment variable is a more secure way of injecting a secret than keeping that in local file-system.
- More-over, it is easier to apply for CI/CD, like we did at @sysdogs.

What do you think, @dhaynespls ?

**Comment by dhaynespls** [comment]
That's fair, we support both for a reason. 

I would phrase it in a way that's something along these lines: 

```
You will need to obtain a scoped API token to publish the worker. You can do this at https://dash.cloudflare.com/profile/api-tokens, and choose the "Edit Cloudflare Workers" template. 

To deploy with the token, 

a) wrangler config
=> enter token 
=> make deploy
b) `CF_API_TOKEN=${token}` make deploy
```

**Comment by limakzi** [comment]
@dhaynespls Approved the new version.
I will fix PR.

**Comment by limakzi** [comment]
Every markdown preprocessor is different, daymn!
It's sufficient, I hope. Review ready.

**Comment by dhaynespls** [comment]
Thank you!

**Pull request merged**
